version: '3.8'
services:
  rabbitmq:
    build: ./rabbitmq
    hostname: 'myrabbit'
    ports:
      - '5672:5672'
      - '15672:15672'
    container_name: rabbitmq
    volumes:
      - rabbit-data:/var/lib/rabbitmq

  frontend-service:
    build: ./frontend-service
    container_name: frontend-service
    depends_on:
      - rabbitmq
    volumes: # for development
      - ./frontend-service:/app
    env_file:
      - ./frontend-service/frontend.env
    ports:
      - 3000:3000

  auth-mongo:
    image: mongo
    container_name: auth-mongo
    volumes:
      - auth-data:/data/db
    ports:
      - 5001:27017

  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      - auth-mongo
      - rabbitmq
    stdin_open: true
    tty: true
    volumes: # for development
      - ./auth-service:/app

  product-mongo:
    image: mongo
    container_name: product-mongo
    volumes:
      - product-data:/data/db
    ports:
      - 5002:27017

  product-service:
    build: ./product-service
    container_name: product-service
    depends_on:
      - rabbitmq
      - product-mongo
    stdin_open: true
    tty: true
    volumes: # for development
      - ./product-service:/app

  cart-mongo:
    image: mongo
    container_name: cart-mongo
    volumes:
      - cart-data:/data/db
    ports:
      - 5003:27017

  cart-service:
      build: ./cart-service
      container_name: cart-service
      depends_on:
        - rabbitmq
        - cart-mongo
      stdin_open: true
      tty: true
      volumes: # for development
        - ./cart-service:/app

  order-mongo:
    image: mongo
    container_name: order-mongo
    volumes:
      - order-data:/data/db
    ports:
      - 5004:27017

volumes:
  auth-data:
  product-data:
  cart-data:
  rabbit-data:
  order-data: