version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '15672:15672'
    container_name: rabbitmq

  auth-mongo:
    image: mongo
    container_name: auth-mongo
    volumes:
      - auth-data:/data/db
    ports:
      - 5002:27017

  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      - auth-mongo
      - rabbitmq
    stdin_open: true
    tty: true
    ports:
      - 5001:5001
    volumes: # for development
      - ./auth-service:/app
      - /app/node_modules

  cart-service:
    build: ./cart-service
    container_name: cart-service
    depends_on:
      - rabbitmq
    stdin_open: true
    tty: true
    volumes: # for development
      - ./cart-service:/app
      - /app/node_modules
    ports:
      - '5004:5004'

  product-mongo:
    image: mongo
    container_name: product-mongo
    volumes:
      - product-data:/data/db
    ports:
      - 5003:27017

  product-service:
    build: ./product-service
    container_name: product-service
    depends_on:
      - rabbitmq
      - product-mongo
    stdin_open: true
    tty: true
    volumes: # for development
      - ./product-service:/app
      - /app/node_modules
    ports:
      - '5000:5000'

volumes:
  auth-data:
  product-data: