version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '15672:15672'
    container_name: rabbitmq

  cart-service:
    build: ./cart-service
    container_name: cart
    depends_on:
      - rabbitmq
    stdin_open: true
    tty: true

  product-service:
    build: ./product-service
    container_name: product
    depends_on:
      - rabbitmq
    stdin_open: true
    tty: true