{
 "title": "Docker Container Metrics",
 "description": "A simple overview of the most important Docker container metrics. (cAdvisor/Prometheus)",
 "tags": [
  "docker",
  "docker metrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(container_cpu_user_seconds_total, job)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(container_cpu_user_seconds_total{job=~\"$job\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(container_cpu_user_seconds_total{instance=~\"$node:(.*)\"}, instance)"
   },
   {
    "name": "Prod",
    "label": "Prod",
    "query": "label_values(container_cpu_user_seconds_total{instance=~\"10.115.220.32:8080|10.115.220.33:8080\", name!=\"cadvisor\"}, name)"
   },
   {
    "name": "NonProd",
    "label": "NonProd",
    "query": "label_values(container_cpu_user_seconds_total{instance=~\"10.115.222.21:8080|10.115.222.22:8080\", name!=\"cadvisor\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "cAdvisor Version Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "cadvisor_version_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mongo Containers Notable Logs (Error, Warning, Fatal)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{container=~\".*-mongo\", severity=~\"W|E|F\"} |= ``"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Usage per Container (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[$interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Memory Usage per Container (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cached Memory per Container (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 22 },
   "targets": [
    {
     "expr": "sum(container_memory_cache{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory RSS per Container (Stacked)",
   "type": "timeseries",
   "description": "Resident Set Size (RSS) represents the portion of memory occupied by a process that is held in main memory (RAM).",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Network Traffic of Containers",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}