{
 "title": "Docker Engine Metrics",
 "description": "Draw some docker metrics",
 "tags": [
  "docker",
  "docker metrics",
  "docker engine"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "instance", "label": "Instance", "query": "engine_daemon_engine_info" }
  ]
 },
 "panels": [
  {
   "title": "Docker Engine Target Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "targets": [
    { "expr": "target_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Docker Engine Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 0 },
   "targets": [
    { "expr": "engine_daemon_engine_info", "legendFormat": "__auto" }
   ]
  },
  { "title": "At a glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Metrics from: $instance",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "instance",
   "targets": [
    { "expr": "$instance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "engine_daemon_engine_cpus_cpus", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Event Subscribers Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "engine_daemon_events_subscribers_total{instance=~'$instance'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Image Builds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 6 },
   "targets": [
    {
     "expr": "builder_builds_triggered_total{instance=~'$instance'}",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(builder_builds_failed_total{instance=~'$instance'}) by (instance)",
     "legendFormat": "Failed"
    }
   ]
  },
  { "title": "Network Actions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total Network Actions (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "engine_daemon_network_actions_seconds_count{instance=~'$instance'}",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Time x Network Action percentile",
   "type": "timeseries",
   "description": "Measuring some percentiles performance",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "actions/s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(engine_daemon_network_actions_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "{{action}} 99"
    },
    {
     "expr": "histogram_quantile(0.90, rate(engine_daemon_network_actions_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "{{action}} 90"
    },
    {
     "expr": "histogram_quantile(0.50, rate(engine_daemon_network_actions_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "{{action}} 50"
    },
    {
     "expr": "histogram_quantile(0.25, rate(engine_daemon_network_actions_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "{{action}} 25"
    }
   ]
  },
  { "title": "Container Actions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Total Container Actions (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine_daemon_container_actions_seconds_count{instance=~'$instance'}",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Time x Container Action percentile",
   "type": "timeseries",
   "description": "Measuring some percentiles performance",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(engine_daemon_container_actions_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "{{action}} 99"
    },
    {
     "expr": "histogram_quantile(0.90, rate(engine_daemon_container_actions_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "{{action}} 90"
    },
    {
     "expr": "histogram_quantile(0.50, rate(engine_daemon_container_actions_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "{{action}} 50"
    },
    {
     "expr": "histogram_quantile(0.25, rate(engine_daemon_container_actions_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "{{action}} 25"
    }
   ]
  }
 ]
}