{
 "title": "Promtail and Loki",
 "tags": [
  "loki",
  "promtail"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Promtail Build Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "promtail_build_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Loki Build Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "expr": "loki_build_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logging activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Promtail Active Files",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "promtail_files_active_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Promtail Sent Entries Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 9 },
   "targets": [
    {
     "expr": "rate(promtail_sent_entries_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Promtail Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(promtail_request_duration_seconds_sum[1m])) > 0",
     "legendFormat": "status code: {{status_code}}"
    }
   ]
  },
  {
   "title": "Promtail Bytes Rate",
   "type": "timeseries",
   "description": "Encoded - bytes encoded and ready to send\nSent - number of bytes sent\nFile - number of bytes read from files\nRead - number of bytes read",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum (rate(promtail_read_bytes_total[$__rate_interval]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum (rate(promtail_sent_bytes_total[$__rate_interval]))",
     "legendFormat": "sent"
    },
    {
     "expr": "sum (rate(promtail_encoded_bytes_total[$__rate_interval]))",
     "legendFormat": "encoded"
    },
    {
     "expr": "sum(promtail_file_bytes_total - promtail_read_bytes_total)",
     "legendFormat": "total lag"
    }
   ]
  },
  {
   "title": "Promtail - Rate of Bytes and Lines Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(promtail_read_bytes_total[$__rate_interval]))",
     "legendFormat": "Bytes Read"
    },
    {
     "expr": "sum(rate(promtail_read_lines_total[$__rate_interval]))",
     "legendFormat": "Lines Read"
    }
   ]
  },
  {
   "title": "Promtail Read Bytes Per Path",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "promtail_read_bytes_total", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "Promtail Read Lines Per Path",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "promtail_read_lines_total", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "Loki (distributor) - Rate of Total Bytes and Entries Received",
   "type": "timeseries",
   "description": "According to documentation, lines_received metric is based on entries not necessarily lines as each entry can have more than one line of text",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(loki_distributor_bytes_received_total[$__rate_interval]))",
     "legendFormat": "Bytes Received"
    },
    {
     "expr": "sum (rate(loki_distributor_lines_received_total[$__rate_interval]))",
     "legendFormat": "Entries Received"
    }
   ]
  },
  {
   "title": "Loki (distributor) - Rate of Batch Appends Sent to Ingesters",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(loki_distributor_ingester_appends_total[$__rate_interval])",
     "legendFormat": "ingester: {{ingester}}"
    }
   ]
  },
  {
   "title": "Loki Store Series Total",
   "type": "stat",
   "description": "Refers to the total number of unique time series currently stored by Loki.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(loki_store_series_total)" }
   ]
  },
  {
   "title": "Loki Internal Message Total",
   "type": "stat",
   "description": "Messages produced by loki itself",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(loki_internal_log_messages_total)"
    }
   ]
  },
  {
   "title": "Loki Ingester Chunk Bytes",
   "type": "stat",
   "description": "Amount of logs in the ingester temporary storage",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "loki_ingester_chunk_stored_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Chunk Store Bytes",
   "type": "stat",
   "description": "Amount of logs in Loki's long term storage backend",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "loki_chunk_store_stored_chunk_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Ingester Streams Actions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "loki_ingester_streams_created_total",
     "legendFormat": "streams created"
    },
    {
     "expr": "loki_ingester_streams_removed_total",
     "legendFormat": "streams removed"
    }
   ]
  },
  {
   "title": "Loki Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(route) (rate(loki_request_duration_seconds_sum[1m])) > 0",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Loki Current Ingester Streams",
   "type": "timeseries",
   "description": "The total number of streams created per tenant. Should not increase too much.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "loki_ingester_memory_streams", "legendFormat": "tenant: {{tenant}}" }
   ]
  },
  {
   "title": "Rate of Chunk Actions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(loki_ingester_chunks_created_total[5m])",
     "legendFormat": "create"
    },
    {
     "expr": "sum by (reason) (rate(loki_ingester_chunks_flushed_total[5m]))",
     "legendFormat": "flush / {{ reason }}"
    },
    {
     "expr": "sum by (fake) (rate(loki_ingester_chunks_stored_total[5m]))",
     "legendFormat": "stored"
    }
   ]
  },
  {
   "title": "Chunk Age",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_age_seconds_bucket[5m])) by (le))",
     "legendFormat": "ages"
    }
   ]
  },
  {
   "title": "Chunk Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_size_bytes_bucket[5m])) by (le))",
     "legendFormat": "chunk size"
    }
   ]
  },
  {
   "title": "Problems",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of error/warning messages logged by Loki itself",
   "type": "timeseries",
   "description": "Total number of messages logged by Loki itself",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(loki_internal_log_messages_total{job=\"loki\",level=~\"error|warn\"}[$__rate_interval])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Error/warning messages logged by Loki itself",
   "type": "logs",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 48 },
   "targets": [
    {
     "expr": "{container=\"loki\"} | unpack | level =~ `error|warn`"
    }
   ]
  },
  {
   "title": "LogQL Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_latency_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Loki Panic ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 9, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "loki_panic_total" }
   ]
  },
  {
   "title": "LogQL  Processed bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_bytes_processed_per_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Loki (distributor) - failed batch appends sent to ingesters",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(loki_distributor_ingester_append_failures_total[1m])*60"
    }
   ]
  },
  {
   "title": "Error/warning messages logged by Promtail",
   "type": "timeseries",
   "description": "Total number of messages logged by Promtail",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(loki_internal_log_messages_total{job=\"promtail\",level=~\"error|warn\"}[$__rate_interval])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Error/warning messages logged by Promtail",
   "type": "logs",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 63 },
   "targets": [
    {
     "expr": "{container=\"promtail\"} | unpack | level =~ `warn|error`"
    }
   ]
  },
  {
   "title": "Promtail - Lag",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "promtail_file_bytes_total - promtail_read_bytes_total > 100000",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Promtail - Rate of Dropped Log Entries",
   "type": "timeseries",
   "description": "Number of log entries dropped because failed to be sent to the Loki ingester after all retries.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(promtail_dropped_entries_total[$__rate_interval])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Promtail - Rate of Dropped Bytes",
   "type": "timeseries",
   "description": "Number of bytes dropped because failed to be sent to the Loki ingester after all retries.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(promtail_dropped_bytes_total[$__rate_interval])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Promtail - Rate of Total Bytes and Entries Dropped ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(promtail_dropped_bytes_total[$__rate_interval]))",
     "legendFormat": "Bytes Dropped"
    },
    {
     "expr": "sum(rate(promtail_dropped_entries_total[$__rate_interval]))",
     "legendFormat": "Entries Dropped"
    }
   ]
  }
 ]
}